version: '3'
services:
  postgresql:
    image: postgres:17.0
    volumes:
      - ./init_db:/docker-entrypoint-initdb.d
    ports:
      - "${DATABASE_PORT}:5432"
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    platform: linux/amd64